<a href="https://colab.research.google.com/github/Mrinal7862/Multi_Classification/blob/main/Multi_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
x, y = make_classification(n_samples=1000, n_features=10, n_redundant=5, n_classes=2, random_state=1 )

In [3]:
x

array([[-0.64531168,  0.61647   , -1.25015835, ..., -1.06658771,
         2.37461271, -1.86522918],
       [ 1.28604405, -1.1777402 , -0.83543021, ..., -0.521761  ,
        -0.33358066,  0.9984341 ],
       [-1.32291085,  1.21943772,  0.33994682, ...,  0.12337878,
         1.02993691, -1.45154652],
       ...,
       [-2.14609948,  1.97778222,  0.58142039, ...,  0.22397655,
         1.63123451, -2.33031202],
       [ 3.00447447, -2.74830426, -2.15788258, ..., -1.38298068,
        -0.5067595 ,  2.16409546],
       [ 3.27598779, -2.99940374, -2.17378725, ..., -1.36543905,
        -0.78936438,  2.50603006]])

In [4]:
y

array([0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,

In [10]:
#  Ovr
model = LogisticRegression(multi_class='ovr', solver='lbfgs')

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=1)

In [7]:
X_train.shape


(700, 10)

In [9]:
X_test.shape

(300, 10)

In [11]:
model.fit(X_train, y_train)

LogisticRegression(multi_class='ovr')

In [13]:
y_pred = model.predict(X_test)

In [14]:
y_pred

array([0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1])

In [17]:
model.predict_proba(X_test)

array([[9.76169700e-01, 2.38303001e-02],
       [1.32247868e-01, 8.67752132e-01],
       [3.81177241e-01, 6.18822759e-01],
       [2.00262695e-02, 9.79973730e-01],
       [1.48689642e-01, 8.51310358e-01],
       [9.99199289e-01, 8.00710722e-04],
       [8.79652670e-03, 9.91203473e-01],
       [4.48351466e-03, 9.95516485e-01],
       [8.78992261e-01, 1.21007739e-01],
       [3.88831720e-02, 9.61116828e-01],
       [9.36366747e-01, 6.36332525e-02],
       [7.15877090e-02, 9.28412291e-01],
       [9.52114166e-01, 4.78858341e-02],
       [9.94625806e-01, 5.37419390e-03],
       [4.57361360e-01, 5.42638640e-01],
       [9.28924275e-01, 7.10757250e-02],
       [1.67132159e-01, 8.32867841e-01],
       [4.54648479e-03, 9.95453515e-01],
       [8.96474878e-01, 1.03525122e-01],
       [9.73430514e-01, 2.65694859e-02],
       [7.26481854e-01, 2.73518146e-01],
       [1.44419274e-01, 8.55580726e-01],
       [3.73468840e-02, 9.62653116e-01],
       [2.78557389e-01, 7.21442611e-01],
       [9.805011

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[112  33]
 [ 17 138]]
0.8333333333333334
              precision    recall  f1-score   support

           0       0.87      0.77      0.82       145
           1       0.81      0.89      0.85       155

    accuracy                           0.83       300
   macro avg       0.84      0.83      0.83       300
weighted avg       0.84      0.83      0.83       300



In [30]:
#  MultiNomial
model = LogisticRegression(multi_class='multinomial', solver='lbfgs')

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=1)

In [32]:
model.fit(X_train, y_train)

LogisticRegression(multi_class='multinomial')

In [33]:
y_pred = model.predict(X_test)

In [34]:
y_pred

array([0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1])

In [35]:
model.predict_proba(X_test)

array([[9.76447010e-01, 2.35529898e-02],
       [1.31349545e-01, 8.68650455e-01],
       [3.80740561e-01, 6.19259439e-01],
       [1.96616574e-02, 9.80338343e-01],
       [1.48243137e-01, 8.51756863e-01],
       [9.99223236e-01, 7.76763931e-04],
       [8.59440173e-03, 9.91405598e-01],
       [4.38064422e-03, 9.95619356e-01],
       [8.80106067e-01, 1.19893933e-01],
       [3.84419870e-02, 9.61558013e-01],
       [9.37139793e-01, 6.28602066e-02],
       [7.09672232e-02, 9.29032777e-01],
       [9.52535148e-01, 4.74648518e-02],
       [9.94740211e-01, 5.25978908e-03],
       [4.57830187e-01, 5.42169813e-01],
       [9.29854147e-01, 7.01458534e-02],
       [1.65837964e-01, 8.34162036e-01],
       [4.42986703e-03, 9.95570133e-01],
       [8.97508876e-01, 1.02491124e-01],
       [9.73930128e-01, 2.60698718e-02],
       [7.27591359e-01, 2.72408641e-01],
       [1.43515365e-01, 8.56484635e-01],
       [3.68356195e-02, 9.63164380e-01],
       [2.77576865e-01, 7.22423135e-01],
       [9.807848

In [36]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[112  33]
 [ 17 138]]
0.8333333333333334
              precision    recall  f1-score   support

           0       0.87      0.77      0.82       145
           1       0.81      0.89      0.85       155

    accuracy                           0.83       300
   macro avg       0.84      0.83      0.83       300
weighted avg       0.84      0.83      0.83       300

